# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: loansdb-deployment
serviceName: loansdb
appLabel: loansdb
appName: loansdb

replicaCount: 1

containerPort: 3306

service:
  type: ClusterIP
  port: 3306
  targetPort: 3306

appname_enabled: false
profile_enabled: false
config_enabled: false
discovery_enabled: false
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: false
datastores_enabled: false
database_enabled: true
  