apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountsdb-deployment
  labels:
    app: accountsdb
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: accountsdb
    
  template:
    metadata:
      labels:
        app: accountsdb
    spec:
      containers:
      - name: accountsdb
        image: mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: eazybank-configmap
              key: MYSQL_ROOT_PASSWORD 
        - name: MYSQL_DATABASE
          value: "accountsdb"
---

apiVersion: v1
kind: Service
metadata:
  name: accountsdb
spec:
  type: ClusterIP
  selector:
    app: accountsdb
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306