apiVersion: apps/v1
kind: Deployment
metadata:
  name: loansdb-deployment
  labels:
    app: loansdb
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: loansdb
    
  template:
    metadata:
      labels:
        app: loansdb
    spec:
      containers:
      - name: loansdb
        image: mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: eazybank-configmap
              key: MYSQL_ROOT_PASSWORD 
        - name: MYSQL_DATABASE
          value: "loansdb"
---

apiVersion: v1
kind: Service
metadata:
  name: loansdb
spec:
  type: ClusterIP
  selector:
    app: loansdb
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306